source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'mysql2', '~> 0.3.18'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'eco'
gem 'coffee-rails', '~> 4.0.0'
gem 'coffee-script-source', '~> 1.8.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'cancancan', '~> 1.9'
gem 'haml-rails'
gem 'html2haml'
gem 'simple_form', '3.1.0.rc1'
gem 'fog', '~> 1.26.0'
gem 'carrierwave'
gem 'figaro'
gem 'datagrid', :git => 'git://github.com/bogdan/datagrid.git'
gem 'kaminari'
gem 'simple-navigation'
gem 'gretel'
gem 'select2-rails'
gem 'adminlte-rails', '~> 1.3.3'
gem 'simple_enum', '~> 2.0.0'
gem 'countries'
gem 'country_select'
gem 'activerecord-import'
gem 'money'
gem 'google_currency'
gem 'money-rails'
gem 'datetimepicker-rails', '>= 3.0.0', :git => 'git://github.com/zpaulovics/datetimepicker-rails.git', :branch => 'tarruda'
gem 'bootstrap-datepicker-rails'
gem 'angularjs-rails', '1.3.10'
gem 'angular-ui-bootstrap-rails', '~> 0.14.0'
gem 'angular-rails-templates', '0.1.3'
gem 'angularjs-rails-resource', '~> 2.0.0'
gem 'sprockets', '2.12.3'
gem 'js-routes'
gem 'datejs-rails', git: 'git://github.com/tuanht/datejs-rails.git'
gem 'monetize'
gem 'highcharts-rails', '~> 4.0.4.1'
gem 'momentjs-rails'
gem 'cocoon'
gem 'activemodel-associations'
gem 'nested_form'
gem 'nokogiri'
gem 'aws-sdk', '1.6.9'
gem 'jquery-datatables-rails', '~> 3.1.1'
gem 'ajax-datatables-rails'
gem 'dsp_reporting', git: 'https://yoosedev:GqQJ3rAQcz@bitbucket.org/yoose/dsp_reporting.git'
gem 'dotimeout-rails'
gem 'validate_url'
gem 'vast_generator', git: 'https://yoosedev:GqQJ3rAQcz@bitbucket.org/yoose/vast_generator.git'
gem 'axlsx_rails', '~> 0.3.0'
gem 'prawn'
gem 'prawn-table'
gem 'prawn-graph'
gem 'gchart', '~> 1.0.0'
gem 'mechanize'
gem 'prawn_rails'
gem 'bootstrap-slider-rails'
gem 'charlock_holmes'
gem 'rails-settings-cached', '0.4.1'
gem 'unicorn'
gem 'activesupport-json_encoder'
gem 'ckeditor_rails'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'date_validator', '~> 0.9.0'
gem 'leaflet-rails'
gem 'net-ssh'
gem 'geocoder', '~> 1.4'
gem 'rest-client', '~> 2.0'
group :test do
  gem 'faker'
  gem 'rspec-rails'
end
group :development do
  gem 'mailcatcher'
  gem 'pry-rails'
  # gem 'spring'
  # gem 'byebug'
  # gem 'quiet_assets'
  # gem 'better_errors'
  # gem 'binding_of_caller'
end
